### ISSUE TITLE
PR built rpms dont have latest code if we keep updating the PR again and again

### ISSUE THREAD

**Issue by shtripat** [Tendrl/tendrl-ci#15] opened 2018-02-28 10:14 UTC
The same PR if it updated again and again, looks like PR build doesnt happen everytime. Should be fixed and everytime there is a push for the PR it should be built again.

**Comment by dahorak** [comment] 2018-03-05 07:37
@shtripat could you please point me to some example, where build doesn't happened for every update? (and especially for the last one)
I've tried to simulate it and it triggered build for every update...

However I find two small (possible) issues:
1) If commits are pushed shortly one after other (to one PR), both built packages are in reality from the later commit (the first build is triggered by the first commit, but when there is `git fetch` command in the job, the second commit is already available in the repository). But this shouldn't be big problem right?

1) The commit id in the package version - `5e526c9` in following case, is not the hash of the last commit, but hash of temporary merge commit to the master branch:
```
tendrl-ui-1.6.0-9920180305T073908.5e526c9.pr809.noarch.rpm
                                  ^^^^^^^
```

For example, the last *real* commit is `b3c40ddcf...`, but the package is from `5e526c9...` which is *temporary* merge to the master branch: 
```
git log -2
commit 5e526c9fafcaee54523c5f406ffa092dda394f59
Merge: 65690ee b3c40dd
Author: dahorak <dahorak@redhat.com>
Date:   Mon Mar 5 07:33:54 2018 +0000

    Merge b3c40ddcf2972e4fa5243e41cc12e573c9165a0c into 65690ee6d4d63361c5ec62b99ff7d970b25a5eb0

commit b3c40ddcf2972e4fa5243e41cc12e573c9165a0c
Author: Daniel Horak <dahorak@redhat.com>
Date:   Mon Mar 5 08:31:15 2018 +0100

    test commit bazzz
```

**Comment by shtripat** [comment] 2018-03-05 08:11
@dahorak yes I had the scenarios where I was pushing changes back-to-back and with `git push --force`.
So I am not sure how you plan to solve the issue.

**Comment by dahorak** [comment] 2018-03-05 08:31
@shtripat please do you have link to the particular PR, where it happened?

**Comment by shtripat** [comment] 2018-03-05 08:48
@dahorak Honestly I don't remember the exact PR. But the ones around the same time when the issue was raised is the PR.

**Comment by dahorak** [comment] 2018-03-05 08:54
@shtripat do you remember the repo? (it will be easier for me to find the particular pr/jobs)

**Comment by shtripat** [comment] 2018-03-05 09:16
It was tendrl-commons

**Comment by dahorak** [comment] 2018-03-05 09:19
ok, thanks ... I'll try to debug it

**Comment by dahorak** [comment] 2018-03-05 09:36
It seems like it might be related to this PR ... I'll try to debug it: https://github.com/Tendrl/commons/pull/836

**Comment by dahorak** [comment] 2018-03-05 12:49
Unfortunately I wasn't able to find any problematic PR/commits...
I've also wasn't able to reproduce any such issue :-/. I've created few testing commits in my testing PR https://github.com/Tendrl/ui/pull/809 and pushed them one after the other and also with some rebase and related usage of `--force` for the git push command, but PR Jobs was always properly triggered for each pushed commit and after all related job finished, the proper packages were available in the expected repo.
Please let me know, if you will face such issue again, so I'll be able to debug it on particular case.

Also please be aware, that every bunch of commits pushed together will trigger one job and the jobs are not concurrently running, so you will have to wait until all the previous jobs finish.

**Comment by dahorak** [comment] 2018-10-25 11:41
As there seems to be no such issue lately (or at least no update), closing this issue.

**Closed as completed by dahorak** 2018-10-25 11:41 UTC
